### ISSUE TITLE
TODO-list

### ISSUE THREAD

**Issue by MarinaMeyta** [MarinaMeyta/infotechs_test_task#1]
- [x] make requirements.txt for virtualenv
- [ ] export/import to text file
- [ ] user's inactivity processing
- [ ] remit/recive money transfer in different QThreads
- [ ] **finish threads after user closes window** - hide windows
